# Generated by Django 3.2.4 on 2021-06-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nduggaapp', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrferItem',
            new_name='OrderItem',
        ),
    ]
